#!/usr/bin/python3

def raise_exception():
    raise TypeError("This is already defined exception.")
